/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package penjualan;

import javax.swing.JOptionPane;

/**
 *
 * @author Yohanes Dwi Listio
 */
public class MenuUtama extends javax.swing.JFrame {

    /**
     * Creates new form MenuUtama
     */
    public MenuUtama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        smLogout = new javax.swing.JMenuItem();
        smKeluarApl = new javax.swing.JMenuItem();
        menuKasir = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        smPembelian = new javax.swing.JMenuItem();
        smTbPembelian = new javax.swing.JMenuItem();
        smReturPembelian = new javax.swing.JMenuItem();
        smTbReturPembelian = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        smPenjualan = new javax.swing.JMenuItem();
        smTbPenjualan = new javax.swing.JMenuItem();
        smReturPenjualan = new javax.swing.JMenuItem();
        smTbReturPenjualan = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("File");

        smLogout.setText("Logout");
        smLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smLogoutActionPerformed(evt);
            }
        });
        jMenu1.add(smLogout);

        smKeluarApl.setText("Keluar Aplikasi");
        smKeluarApl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smKeluarAplActionPerformed(evt);
            }
        });
        jMenu1.add(smKeluarApl);

        jMenuBar1.add(jMenu1);

        menuKasir.setText("Kasir");
        menuKasir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuKasirActionPerformed(evt);
            }
        });
        jMenuBar1.add(menuKasir);

        jMenu3.setText("Transaksi Pembelian");

        smPembelian.setText("Pembelian");
        smPembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smPembelianActionPerformed(evt);
            }
        });
        jMenu3.add(smPembelian);

        smTbPembelian.setText("Tabel Pembelian");
        smTbPembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smTbPembelianActionPerformed(evt);
            }
        });
        jMenu3.add(smTbPembelian);

        smReturPembelian.setText("Retur Pembelian");
        smReturPembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smReturPembelianActionPerformed(evt);
            }
        });
        jMenu3.add(smReturPembelian);

        smTbReturPembelian.setText("Tabel Retur Pembelian");
        smTbReturPembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smTbReturPembelianActionPerformed(evt);
            }
        });
        jMenu3.add(smTbReturPembelian);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Transaksi Penjualan");

        smPenjualan.setText("Penjualan");
        jMenu4.add(smPenjualan);

        smTbPenjualan.setText("Tabel Penjualan");
        jMenu4.add(smTbPenjualan);

        smReturPenjualan.setText("Retur Penjualan");
        jMenu4.add(smReturPenjualan);

        smTbReturPenjualan.setText("Retur Penjualan");
        jMenu4.add(smTbReturPenjualan);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 772, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 438, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void smLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smLogoutActionPerformed
        // TODO add your handling code here:
        int input = JOptionPane.showConfirmDialog(null, "Logout dari aplikasi?", "Yakin ingin logout?", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (input == JOptionPane.YES_OPTION) {
            new LoginFrame().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_smLogoutActionPerformed

    private void smKeluarAplActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smKeluarAplActionPerformed
        // TODO add your handling code here:
    int input = JOptionPane.showConfirmDialog(null, "Keluar dari aplikasi?", "Yakin ingin keluar?", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (input == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_smKeluarAplActionPerformed

    private void smTbReturPembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smTbReturPembelianActionPerformed
        // TODO add your handling code here:
        new penjualan.pembelian.Tabelreturpembelian_frame().setVisible(true);
    }//GEN-LAST:event_smTbReturPembelianActionPerformed

    private void smPembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smPembelianActionPerformed
        // TODO add your handling code here:
        new penjualan.pembelian.Pembeliantunai_frame().setVisible(true);
    }//GEN-LAST:event_smPembelianActionPerformed

    private void smTbPembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smTbPembelianActionPerformed
        // TODO add your handling code here:
        new penjualan.pembelian.Tabelpembelian_frame().setVisible(true);
    }//GEN-LAST:event_smTbPembelianActionPerformed

    private void smReturPembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smReturPembelianActionPerformed
        // TODO add your handling code here:
        new penjualan.pembelian.Returpembelian_frame().setVisible(true);
    }//GEN-LAST:event_smReturPembelianActionPerformed

    private void menuKasirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuKasirActionPerformed
        // TODO add your handling code here:
        new penjualan.kasir.Master().setVisible(true);
    }//GEN-LAST:event_menuKasirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuKasir;
    private javax.swing.JMenuItem smKeluarApl;
    private javax.swing.JMenuItem smLogout;
    private javax.swing.JMenuItem smPembelian;
    private javax.swing.JMenuItem smPenjualan;
    private javax.swing.JMenuItem smReturPembelian;
    private javax.swing.JMenuItem smReturPenjualan;
    private javax.swing.JMenuItem smTbPembelian;
    private javax.swing.JMenuItem smTbPenjualan;
    private javax.swing.JMenuItem smTbReturPembelian;
    private javax.swing.JMenuItem smTbReturPenjualan;
    // End of variables declaration//GEN-END:variables
}
